[server]
headless = true
address = "localhost"
port = 8503
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8503

[theme]
primaryColor = "#00ffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
font = "sans serif"

[global]
developmentMode = false
unitTest = false